apiVersion: v1
kind: Service
metadata:
  name: "{{#toLowerCase applicationName}}{{/toLowerCase}}-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  {{#has language 'java'}}
  - name: http
    port: 9080
  - name: https
    port: 9443
  {{/has}}
  {{#has language 'spring'}}
  - name: http
    port: 8080
  {{/has}}

  selector:
    app: "{{#toLowerCase applicationName}}{{/toLowerCase}}-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{#toLowerCase applicationName}}{{/toLowerCase}}-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{#toLowerCase applicationName}}{{/toLowerCase}}-selector"
    spec:
      containers:
      - name: {{#toLowerCase applicationName}}{{/toLowerCase}}
        image: {{#toLowerCase applicationName}}{{/toLowerCase}}:latest
        readinessProbe:
          httpGet:
          {{! healthEndpoint is configured in the index.js and is different for basicweb}}
          {{#has language 'java'}}
            path: /{{applicationName}}/{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 9080
          {{/has}}
          {{#has language 'spring'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 8080
          {{/has}}
          initialDelaySeconds: 20
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
