version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-tools
    tty: true
    image: "{{image}}"
    container_name: "{{containerName}}"
    ports: {{#each ports}}
      - "{{this}}:{{this}}"{{/each}}
    volumes:
      - .:/app {{#ifCond images.length '>' 0}}
    links: {{#each images}}
      -  {{this}}{{/each}}{{/ifCond}}
    environment: {{#each envs as |value key|}}
      {{key}}: {{value}}{{/each}}; {{#each images}}
  {{this}}:
    image: {{this}}
{{/each}}
