version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "{{image}}"
    container_name: "{{containerName}}"
    ports: {{#each ports}}
      - "{{this}}:{{this}}"{{/each}} {{#ifCond images.length '>' 0}}
    links: {{#each images}}
      - {{this}}{{/each}}{{/ifCond}}
    environment: {{log envs}}{{#each envs as |value key|}}
      {{key}}: {{value}}{{/each}} {{#each images}}
  {{this}}:
    image: {{this}}
  {{/each}}
