{{tag ' if .Values.base.enabled '}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{tag '  .Chart.Name '}}-basedeployment"
  labels:
    chart: '{{tag ' .Chart.Name '}}-{{tag ' .Chart.Version | replace "+" "_" '}}'
spec:
  replicas: {{tag ' .Values.base.replicaCount '}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{tag ' .Values.revisionHistoryLimit '}}
  template:
    metadata:
      labels:
        app: "{{tag '  .Chart.Name '}}-selector"
        version: "base"
    spec:
      containers:
      - name: "{{tag '  .Chart.Name  '}}"
        image: "{{tag ' .Values.image.repository '}}:{{tag ' .Values.base.image.tag '}}"
        imagePullPolicy: {{tag ' .Values.image.pullPolicy '}}
        livenessProbe:
          httpGet:
            {{#has deployment.backendPlatform 'SPRING'}}
            path: /actuator/health
            {{/has}}
            {{#has deployment.backendPlatform 'JAVA'}}
            path: /health
            {{/has}}
            port: {{tag ' .Values.service.servicePort '}}
          initialDelaySeconds: {{tag ' .Values.livenessProbe.initialDelaySeconds'}}
          periodSeconds: {{tag ' .Values.livenessProbe.periodSeconds'}}
        resources:
          requests:
            cpu: "{{tag ' .Values.image.resources.requests.cpu '}}"
            memory: "{{tag ' .Values.image.resources.requests.memory '}}"
        env:
          - name: PORT
            value : "{{tag ' .Values.service.servicePort '}}"
{{tag ' end '}}
