{{ if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "prometheus-config-{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app: "{{ .Chart.Name }}-selector"
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "{{ .Chart.Name }}-selector"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "{{ .Chart.Name }}-selector"
            action: keep
{{ end }}